import { AudioSample } from '../../types';

/**
 * Realistic de-identified clinical speech audio samples representing
 * the structure and clinical domains of the Intron AfriHealth MultiBench.
 *
 * Privacy Guarantees:
 * - Zero PII / Patient identifiers
 * - De-identified Speaker IDs (e.g. SPK_NG_HA_101)
 * - Synthetic/consented medical scenarios vetted for medical safety
 */
export const CLINICAL_AUDIO_SAMPLES: AudioSample[] = [
  {
    id: 'AHMB-HA-001',
    title: 'Hausa Antenatal Nutrition & Iron Supplement Guidance',
    clinicalDomain: 'maternal_health',
    durationSec: 8.4,
    language: 'ha',
    accent: 'Kano Urban Hausa',
    speakerMetadata: {
      speakerId: 'SPK_NG_HA_101',
      region: 'Kano, Northern Nigeria',
      dialect: 'Standard Kananci',
      deIdentified: true,
    },
    referenceTranscript: 'Kina bukatar shan maganin iron da folic acid a kowace rana don karfafa jinin ki da lafiyar jaririn.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-HA-002',
    title: 'Hausa Pediatric Malaria Triage & Fever Management',
    clinicalDomain: 'malaria',
    durationSec: 9.1,
    language: 'ha',
    accent: 'Kaduna Peri-Urban Hausa',
    speakerMetadata: {
      speakerId: 'SPK_NG_HA_102',
      region: 'Kaduna, Northern Nigeria',
      dialect: 'Standard Hausa',
      deIdentified: true,
    },
    referenceTranscript: 'Idan yaron yana da zazzabi mai tsanani da amai, a kawo shi asibiti nan da nan don gwajin malaria.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-CS-HA-003',
    title: 'Nigerian English + Hausa Code-Switched Clinic Consultation',
    clinicalDomain: 'triage',
    durationSec: 10.2,
    language: 'en',
    accent: 'Northern Nigerian Accented English / Hausa',
    speakerMetadata: {
      speakerId: 'SPK_NG_CS_103',
      region: 'Abuja FCT, Nigeria',
      dialect: 'Code-Switched Medical Lingua Franca',
      deIdentified: true,
    },
    referenceTranscript: 'The patient took two tablets of paracetamol yau da safe, but zazzabi still refused to subside.',
    hasCodeSwitching: true,
    codeSwitchDetails: {
      primaryLang: 'en',
      switchedLang: 'ha',
      switchCount: 2,
    },
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-YO-004',
    title: 'Yoruba Hypertension Lifestyle & Salt Reduction Counseling',
    clinicalDomain: 'cardiology',
    durationSec: 9.5,
    language: 'yo',
    accent: 'Ibadan Oyo Yoruba',
    speakerMetadata: {
      speakerId: 'SPK_NG_YO_201',
      region: 'Oyo State, Southwestern Nigeria',
      dialect: 'Standard Yoruba',
      deIdentified: true,
    },
    referenceTranscript: 'Ẹ dín iyọ̀ kù nínú oúnjẹ yín, kí ẹ sì máa mu òògùn ẹ̀jẹ̀ ríru yín lẹ́ẹ̀kan lójúmọ́ láìsí ìdádúró.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-YO-005',
    title: 'Yoruba Community Cholera Prevention & Oral Rehydration',
    clinicalDomain: 'triage',
    durationSec: 8.8,
    language: 'yo',
    accent: 'Lagos Mainland Yoruba',
    speakerMetadata: {
      speakerId: 'SPK_NG_YO_202',
      region: 'Lagos, Nigeria',
      dialect: 'Lagosian Yoruba',
      deIdentified: true,
    },
    referenceTranscript: 'Ẹ máa se omi mímu yín dáadáa, kí ẹ sì pèsè omi iyọ̀ àti ṣúgà fún ẹni tí ń gbẹ́gbẹ́.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-CS-YO-006',
    title: 'Nigerian English + Yoruba Code-Switched Emergency Room Intake',
    clinicalDomain: 'triage',
    durationSec: 9.8,
    language: 'en',
    accent: 'Lagos Accented English / Yoruba',
    speakerMetadata: {
      speakerId: 'SPK_NG_CS_203',
      region: 'Lagos, Nigeria',
      dialect: 'Urban Code-Switching',
      deIdentified: true,
    },
    referenceTranscript: 'Please nurse, check the blood pressure now now, ara n gbọ̀n and she has severe headache since yesterday.',
    hasCodeSwitching: true,
    codeSwitchDetails: {
      primaryLang: 'en',
      switchedLang: 'yo',
      switchCount: 1,
    },
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-IG-007',
    title: 'Igbo Postpartum Danger Signs & Neonatal Jaundice Check',
    clinicalDomain: 'maternal_health',
    durationSec: 9.2,
    language: 'ig',
    accent: 'Enugu Central Igbo',
    speakerMetadata: {
      speakerId: 'SPK_NG_IG_301',
      region: 'Enugu, Southeastern Nigeria',
      dialect: 'Central Igbo',
      deIdentified: true,
    },
    referenceTranscript: 'Ọ bụrụ na ahụ ọkụ abịa ma ọ bụ nwa amụrụ ọhụrụ enwee anya edo edo, kpọtara ya ngwa ngwa n\'ụlọ ọgwụ.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-IG-008',
    title: 'Igbo Diabetes Blood Sugar Monitoring & Insulin Adherence',
    clinicalDomain: 'pharmacy',
    durationSec: 8.6,
    language: 'ig',
    accent: 'Owerri Imo Igbo',
    speakerMetadata: {
      speakerId: 'SPK_NG_IG_302',
      region: 'Imo State, Southeastern Nigeria',
      dialect: 'Central Igbo',
      deIdentified: true,
    },
    referenceTranscript: 'Nyochaa ọkwa shuga dị n\'ọbara gị n\'ụtụtụ tupu i rie nri ma ghara ịkwụsị ịgba insulin ahụ.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-CS-IG-009',
    title: 'Nigerian English + Igbo Code-Switched Clinic Triage',
    clinicalDomain: 'triage',
    durationSec: 10.4,
    language: 'en',
    accent: 'Eastern Nigerian English / Igbo',
    speakerMetadata: {
      speakerId: 'SPK_NG_CS_303',
      region: 'Anambra State, Nigeria',
      dialect: 'Bilingual Medical Colloquial',
      deIdentified: true,
    },
    referenceTranscript: 'The doctor said we must admit him because ahụ ọkụ is rising and he cannot keep any fluids down.',
    hasCodeSwitching: true,
    codeSwitchDetails: {
      primaryLang: 'en',
      switchedLang: 'ig',
      switchCount: 1,
    },
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-EN-010',
    title: 'Nigerian Accented English Clinical Discharge Instructions',
    clinicalDomain: 'pharmacy',
    durationSec: 9.0,
    language: 'en',
    accent: 'Standard Nigerian English (Medical Professional)',
    speakerMetadata: {
      speakerId: 'SPK_NG_EN_401',
      region: 'Benin City, Nigeria',
      dialect: 'Professional Nigerian English',
      deIdentified: true,
    },
    referenceTranscript: 'Take this oral antibiotic capsule every eight hours with plenty of water for seven complete days.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-FR-011',
    title: 'Francophone West African Maternal Health Vaccination Notice',
    clinicalDomain: 'vaccination',
    durationSec: 8.9,
    language: 'fr',
    accent: 'Senegalese Accented French',
    speakerMetadata: {
      speakerId: 'SPK_SN_FR_501',
      region: 'Dakar, Senegal',
      dialect: 'West African French',
      deIdentified: true,
    },
    referenceTranscript: 'Le vaccin contre le tétanos et la poliomyélite protège votre nouveau-né contre les complications graves.',
    hasCodeSwitching: false,
    consentVerified: true,
    piiScrubbed: true,
  },
  {
    id: 'AHMB-CS-FR-012',
    title: 'Cameroonian French + English Code-Switched Community Health Message',
    clinicalDomain: 'triage',
    durationSec: 9.6,
    language: 'fr',
    accent: 'Cameroonian Bilingual French/English',
    speakerMetadata: {
      speakerId: 'SPK_CM_CS_502',
      region: 'Douala, Cameroon',
      dialect: 'Cameroonian Bilingual Vernacular',
      deIdentified: true,
    },
    referenceTranscript: 'Il faut boire beaucoup d\'eau propre parce que this heatwave can quickly cause severe dehydration.',
    hasCodeSwitching: true,
    codeSwitchDetails: {
      primaryLang: 'fr',
      switchedLang: 'en',
      switchCount: 1,
    },
    consentVerified: true,
    piiScrubbed: true,
  },
];
