import React, { useState } from 'react';
import { X, Download, Copy, Check, FileText } from 'lucide-react';
import { BenchmarkRun } from '../types';

interface ExportReportModalProps {
  run: BenchmarkRun;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ run, onClose }) => {
  const [copied, setCopied] = useState(false);
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');

  const generateMarkdownReport = (): string => {
    return `# AfriVoice Studio - Speech Model Benchmark Evaluation Report
**Run ID:** ${run.runId}  
**Date:** ${new Date(run.timestamp).toUTCString()}  
**Evaluated Models:** ${run.models.join(', ')}  
**Sample Count:** ${run.sampleCount} clinical instances  
**Languages Evaluated:** ${run.languages.map(l => l.toUpperCase()).join(', ')}  

---

## 1. Executive Summary & Macro Averages

| Model | Macro-Avg WER | Macro-Avg CER | Avg Latency (ms) | Success Rate (%) |
| :--- | :---: | :---: | :---: | :---: |
${run.models.map(m => {
  const wer = (run.macroAverageWer[m] * 100).toFixed(2);
  const cer = (run.macroAverageCer[m] * 100).toFixed(2);
  const lat = run.averageLatencyMs[m];
  const succ = run.successRate[m];
  return `| **${m.toUpperCase()}** | ${wer}% | ${cer}% | ${lat} ms | ${succ}% |`;
}).join('\n')}

---

## 2. Evaluation Methodology & Reproducibility
- **Evaluation Unit:** Audio utterance / reference transcription pairing from consented, de-identified clinical African speech.
- **Word Error Rate (WER):** Standard Levenshtein edit distance computed on lowercased, punctuation-normalized tokens: \`WER = (S + D + I) / N\`.
- **Character Error Rate (CER):** Character-level Levenshtein edit distance normalized by reference character count.
- **African Diacritic Protocol:** Analysis accounts for tonal markers in Hausa, Igbo, and Yoruba orthography.
- **Code-Switching Layer:** Intra-utterance code-switch transitions identified and tagged with transparent \`Model-Inferred\` confidence metrics.

---

## 3. Privacy & Clinical Safety Statement
- **De-Identification:** All personal identifiers, clinical facility names, and patient data have been scrubbed in accordance with IRB protocols.
- **Clinical Disclaimer:** This benchmark evaluates speech-to-text accuracy and communication clarity. Outputs are not medical advice or diagnostic prescriptions.

*Report generated by AfriVoice Studio - Sahara CodeSwitch Africa Challenge.*
`;
  };

  const generateJsonReport = (): string => {
    return JSON.stringify(
      {
        benchmarkTitle: 'AfriVoice Studio - Sahara CodeSwitch Africa Challenge',
        runId: run.runId,
        timestamp: run.timestamp,
        models: run.models,
        sampleCount: run.sampleCount,
        languages: run.languages,
        macroAverageWer: run.macroAverageWer,
        macroAverageCer: run.macroAverageCer,
        averageLatencyMs: run.averageLatencyMs,
        successRate: run.successRate,
        resultsSummary: run.results.map(r => ({
          sampleId: r.sampleId,
          modelResults: r.modelResults,
        })),
        privacyGuaranteed: true,
        deIdentified: true,
      },
      null,
      2
    );
  };

  const reportContent = format === 'markdown' ? generateMarkdownReport() : generateJsonReport();

  const handleCopy = () => {
    navigator.clipboard.writeText(reportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportContent], {
      type: format === 'markdown' ? 'text/markdown' : 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `afrivoice-benchmark-${run.runId}.${format === 'markdown' ? 'md' : 'json'}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-xs">
      <div className="bg-white border border-slate-200 rounded-xl max-w-3xl w-full p-5 shadow-xl text-slate-800 max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between pb-3 border-b border-slate-200">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-slate-600" />
            <h3 className="text-base font-bold text-slate-900">Export Benchmark Report</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-md text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex flex-wrap items-center justify-between gap-2 my-3">
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setFormat('markdown')}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                format === 'markdown'
                  ? 'bg-slate-900 text-white'
                  : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
              }`}
            >
              Markdown (.md)
            </button>
            <button
              onClick={() => setFormat('json')}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                format === 'json'
                  ? 'bg-slate-900 text-white'
                  : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
              }`}
            >
              Structured JSON
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-slate-300 hover:bg-slate-50 text-xs font-medium text-slate-700 transition-colors shadow-xs"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-700 hover:bg-emerald-800 text-xs font-medium text-white transition-colors shadow-xs"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        <div className="flex-1 min-h-[300px] overflow-y-auto bg-slate-50 p-4 rounded-lg border border-slate-200 font-mono text-xs text-slate-800 leading-relaxed select-all">
          <pre className="whitespace-pre-wrap">{reportContent}</pre>
        </div>

        <div className="pt-3 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500">
          <span>De-identified dataset · IRB consented · Zero PII exported</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-800 font-medium transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
