<script setup lang="ts">
import { ref, computed } from 'vue';
import { X, Download, Copy, Check, FileText, AlertCircle } from 'lucide-vue-next';
import type { BenchmarkRun } from '../types';

const props = defineProps<{
  run: BenchmarkRun;
}>();

defineEmits<{ (e: 'close'): void }>();

const copied = ref(false);
const copyError = ref<string | null>(null);
const format = ref<'markdown' | 'json'>('markdown');

function generateMarkdownReport(): string {
  const run = props.run;
  const rows = run.models
    .map((m) => {
      const wer = run.macroAverageWer[m] != null ? `${(run.macroAverageWer[m]! * 100).toFixed(2)}%` : 'Not configured';
      const cer = run.macroAverageCer[m] != null ? `${(run.macroAverageCer[m]! * 100).toFixed(2)}%` : 'Not configured';
      const acc = run.macroAverageAccuracy[m] != null ? `${(run.macroAverageAccuracy[m]! * 100).toFixed(2)}%` : 'Not configured';
      const lat = run.averageLatencyMs[m] != null ? `${run.averageLatencyMs[m]} ms` : '—';
      const succ = run.successRate[m] ?? 0;
      return `| **${m.toUpperCase()}** | ${wer} | ${cer} | ${acc} | ${lat} | ${succ}% |`;
    })
    .join('\n');

  return `# AfriVoice Studio - Speech Model Benchmark Evaluation Report
**Run ID:** ${run.runId}
**Date:** ${new Date(run.timestamp).toUTCString()}
**Evaluated Models:** ${run.models.join(', ')}
**Sample Count:** ${run.sampleCount} clinical instances
**Languages Evaluated:** ${run.languages.map((l) => l.toUpperCase()).join(', ')}

---

## 1. Executive Summary & Macro Averages

| Model | Macro-Avg WER | Macro-Avg CER | Accuracy | Avg Latency (ms) | Success Rate (%) |
| :--- | :---: | :---: | :---: | :---: | :---: |
${rows}

---

## 2. Evaluation Methodology & Reproducibility
- **Evaluation Unit:** Audio utterance / reference transcription pairing from consented, de-identified clinical African speech.
- **Word Error Rate (WER):** Standard Levenshtein edit distance computed on lowercased, punctuation-normalized tokens: \`WER = (S + D + I) / N\`.
- **Character Error Rate (CER):** Character-level Levenshtein edit distance normalized by reference character count.
- **Accuracy:** Word-level accuracy, defined as \`1 - WER\`, clamped to [0, 1].
- **African Diacritic Protocol:** Analysis accounts for tonal markers in Hausa, Igbo, and Yoruba orthography.
- **Code-Switching Layer:** Intra-utterance code-switch transitions identified and tagged with transparent \`Model-Inferred\` confidence metrics.

---

## 3. Privacy & Clinical Safety Statement
- **De-Identification:** All personal identifiers, clinical facility names, and patient data have been scrubbed in accordance with IRB protocols.
- **Clinical Disclaimer:** This benchmark evaluates speech-to-text accuracy and communication clarity. Outputs are not medical advice or diagnostic prescriptions.

*Report generated by AfriVoice Studio - Sahara CodeSwitch Africa Challenge.*
`;
}

function generateJsonReport(): string {
  const run = props.run;
  return JSON.stringify(
    {
      benchmarkTitle: 'AfriVoice Studio - Sahara CodeSwitch Africa Challenge',
      runId: run.runId,
      timestamp: run.timestamp,
      models: run.models,
      sampleCount: run.sampleCount,
      languages: run.languages,
      macroAverageWer: run.macroAverageWer,
      macroAverageCer: run.macroAverageCer,
      macroAverageAccuracy: run.macroAverageAccuracy,
      averageLatencyMs: run.averageLatencyMs,
      successRate: run.successRate,
      resultsSummary: run.results.map((r) => ({
        sampleId: r.sampleId,
        modelResults: r.modelResults,
      })),
      privacyGuaranteed: true,
      deIdentified: true,
    },
    null,
    2
  );
}

const reportContent = computed(() => (format.value === 'markdown' ? generateMarkdownReport() : generateJsonReport()));

async function handleCopy() {
  copyError.value = null;
  try {
    await navigator.clipboard.writeText(reportContent.value);
    copied.value = true;
    setTimeout(() => (copied.value = false), 2000);
  } catch (err) {
    console.error('Clipboard write failed', err);
    copyError.value = 'Could not copy to clipboard. Your browser may be blocking clipboard access.';
  }
}

function handleDownload() {
  const blob = new Blob([reportContent.value], {
    type: format.value === 'markdown' ? 'text/markdown' : 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `afrivoice-benchmark-${props.run.runId}.${format.value === 'markdown' ? 'md' : 'json'}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
</script>

<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-xs">
    <div class="bg-white border border-slate-200 rounded-xl max-w-3xl w-full p-5 shadow-xl text-slate-800 max-h-[90vh] flex flex-col">
      <div class="flex items-center justify-between pb-3 border-b border-slate-200">
        <div class="flex items-center gap-2">
          <FileText class="w-5 h-5 text-slate-600" />
          <h3 class="text-base font-bold text-slate-900">Export Benchmark Report</h3>
        </div>
        <button
          class="p-1 rounded-md text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
          @click="$emit('close')"
        >
          <X class="w-5 h-5" />
        </button>
      </div>

      <div class="flex flex-wrap items-center justify-between gap-2 my-3">
        <div class="flex items-center gap-1.5">
          <button
            class="px-3 py-1.5 rounded-lg text-xs font-medium transition-colors"
            :class="format === 'markdown' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'"
            @click="format = 'markdown'"
          >
            Markdown (.md)
          </button>
          <button
            class="px-3 py-1.5 rounded-lg text-xs font-medium transition-colors"
            :class="format === 'json' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'"
            @click="format = 'json'"
          >
            Structured JSON
          </button>
        </div>

        <div class="flex items-center gap-2">
          <button
            class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-slate-300 hover:bg-slate-50 text-xs font-medium text-slate-700 transition-colors shadow-xs"
            @click="handleCopy"
          >
            <Check v-if="copied" class="w-3.5 h-3.5 text-emerald-600" />
            <Copy v-else class="w-3.5 h-3.5 text-slate-500" />
            <span>{{ copied ? 'Copied' : 'Copy' }}</span>
          </button>
          <button
            class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-700 hover:bg-emerald-800 text-xs font-medium text-white transition-colors shadow-xs"
            @click="handleDownload"
          >
            <Download class="w-3.5 h-3.5" />
            <span>Download File</span>
          </button>
        </div>
      </div>

      <div v-if="copyError" class="mb-2 p-2.5 rounded-lg bg-rose-50 border border-rose-200 text-xs text-rose-800 flex items-start gap-2">
        <AlertCircle class="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
        <span>{{ copyError }}</span>
      </div>

      <div class="flex-1 min-h-[300px] overflow-y-auto bg-slate-50 p-4 rounded-lg border border-slate-200 font-mono text-xs text-slate-800 leading-relaxed select-all">
        <pre class="whitespace-pre-wrap">{{ reportContent }}</pre>
      </div>

      <div class="pt-3 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500">
        <span>De-identified dataset · IRB consented · Zero PII exported</span>
        <button
          class="px-4 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-800 font-medium transition-colors"
          @click="$emit('close')"
        >
          Close
        </button>
      </div>
    </div>
  </div>
</template>
