import { Modality } from '@google/genai';
import { getGeminiClient, isQuotaExceededError } from './geminiClient';
import { pcmToWavBuffer } from './pcmToWav';
import { normalizeQuietAudio } from '../asr/audioPreprocess';
import type { LanguageCode } from '../../types';

export interface SynthesizeResult {
  success: boolean;
  audioBase64?: string;
  mimeType?: string;
  durationSec?: number;
  error?: string;
  quotaExceeded?: boolean;
  fromCache?: boolean;
}

// In-memory cache, process lifetime only. The benchmark re-synthesizes the
// exact same (text, language) reference clip every time it re-runs the same
// sample set, which needlessly burns Gemini's scarce 10-request/day free-tier
// TTS quota on identical output. Reusing the previous real result for an
// identical input is caching, not fabrication — the audio was still
// genuinely generated by Gemini once.
const referenceAudioCache = new Map<string, SynthesizeResult>();

/**
 * Synthesizes neutral reference audio purely so the benchmark runner has a
 * real audio clip to hand to each ASR provider. This is deliberately
 * separate from the richer voice-generation call in /api/tts/generate
 * (which supports emotion/voice selection for the product feature) — the
 * benchmark only needs one consistent, neutral rendering of the ground-truth
 * transcript, reused identically across every model under comparison.
 */
export async function synthesizeReferenceAudio(text: string, language: LanguageCode): Promise<SynthesizeResult> {
  const cacheKey = `${language}::${text}`;
  const cached = referenceAudioCache.get(cacheKey);
  if (cached) {
    return { ...cached, fromCache: true };
  }

  const ai = getGeminiClient();
  if (!ai) {
    return {
      success: false,
      error: 'GEMINI_API_KEY is not configured, so no reference audio can be synthesized for this benchmark run.',
    };
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-tts-preview',
      contents: [{ parts: [{ text: `Speak clearly and naturally in ${language}: ${text}` }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Kore' } },
        },
      },
    });

    const rawPcmBase64 = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!rawPcmBase64) {
      throw new Error('Gemini model did not return audio data in candidates response.');
    }

    const pcmRawBuffer = Buffer.from(rawPcmBase64, 'base64');
    const wavBuffer = pcmToWavBuffer(pcmRawBuffer, 24000, 1, 16);
    const durationSec = Math.max(1, Math.round((pcmRawBuffer.length / (24000 * 2)) * 10) / 10);

    // Boost quiet renderings before handing this off to any ASR provider —
    // a quiet clip is more likely to be mistranscribed or hallucinated on.
    const { buffer: audioBuffer } = normalizeQuietAudio(wavBuffer);

    const result: SynthesizeResult = {
      success: true,
      audioBase64: audioBuffer.toString('base64'),
      mimeType: 'audio/wav',
      durationSec,
    };
    referenceAudioCache.set(cacheKey, result);
    return result;
  } catch (err) {
    return {
      success: false,
      quotaExceeded: isQuotaExceededError(err),
      error: err instanceof Error ? err.message : 'Gemini reference audio synthesis failed.',
    };
  }
}
