import { VoiceOption, ProviderCapability, LanguageCode } from '../../types';

export const PROVIDER_CAPABILITIES: Record<string, ProviderCapability> = {
  sahara: {
    id: 'sahara',
    name: 'Intron Sahara TTS',
    description: 'Specialized state-of-the-art African speech synthesis with native phonemes and tonal support for Hausa, Igbo, Yoruba, and Nigerian English.',
    supportedLanguages: ['ha', 'ig', 'yo', 'en'],
    supportsAfricanTones: true,
    supportsCodeSwitching: true,
    requiresApiKey: true,
    apiKeyEnvVar: 'SAHARA_API_KEY',
    isConfigured: false, // Updated dynamically from /api/providers/status
    statusMessage: 'Awaiting SAHARA_API_KEY in server secrets',
    badge: 'Native African Speech',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini 3.1 Flash TTS',
    description: 'Multimodal generative voice model by Google DeepMind with high emotional expressiveness across international and African languages.',
    supportedLanguages: ['en', 'fr', 'es', 'zh', 'hi', 'ha', 'ig', 'yo'],
    supportsAfricanTones: true,
    supportsCodeSwitching: true,
    requiresApiKey: true,
    apiKeyEnvVar: 'GEMINI_API_KEY',
    isConfigured: false, // Updated dynamically
    statusMessage: 'Awaiting GEMINI_API_KEY in server secrets',
    badge: 'Expressive Generative AI',
  },
  browser: {
    id: 'browser',
    name: 'Device Native Web Speech',
    description: 'Client-side synthesized speech using your browser\'s installed voices. Available immediately with zero external credentials.',
    supportedLanguages: ['en', 'fr', 'es', 'zh', 'hi'],
    supportsAfricanTones: false,
    supportsCodeSwitching: false,
    requiresApiKey: false,
    apiKeyEnvVar: 'NONE',
    isConfigured: true,
    statusMessage: 'Ready (Local device speech synthesis)',
    badge: 'Zero-Config Fallback',
  },
};

export const AVAILABLE_VOICES: VoiceOption[] = [
  // Intron Sahara Voices (Native African)
  {
    id: 'sahara-ha-female-1',
    name: 'Amina (Hausa - Natural)',
    provider: 'sahara',
    gender: 'female',
    accent: 'Kano Urban Hausa',
    language: 'ha',
    supportedStyles: ['Healthcare Compassionate', 'Community Broadcast', 'Clear Instructional'],
    recommendedFor: 'Maternal health announcements, triage, and radio public education in Northern Nigeria and Niger.',
  },
  {
    id: 'sahara-ha-male-1',
    name: 'Danjuma (Hausa - Authoritative)',
    provider: 'sahara',
    gender: 'male',
    accent: 'Kaduna Hausa',
    language: 'ha',
    supportedStyles: ['Public Health Alert', 'Educational Guide'],
    recommendedFor: 'Community health announcements and immunization mobilizations.',
  },
  {
    id: 'sahara-yo-female-1',
    name: 'Folashade (Yoruba - Melodic)',
    provider: 'sahara',
    gender: 'female',
    accent: 'Ibadan Standard Yoruba',
    language: 'yo',
    supportedStyles: ['Counseling Tone', 'Warm Antenatal', 'Clinical Advice'],
    recommendedFor: 'Patient counseling, maternal checkups, and elder healthcare literacy in Southwestern Nigeria.',
  },
  {
    id: 'sahara-yo-male-1',
    name: 'Adebayo (Yoruba - Clear)',
    provider: 'sahara',
    gender: 'male',
    accent: 'Lagos Urban Yoruba',
    language: 'yo',
    supportedStyles: ['Instructional', 'Prescription Explanation'],
    recommendedFor: 'Pharmacy dosage adherence and clinical triage communication.',
  },
  {
    id: 'sahara-ig-female-1',
    name: 'Chidinma (Igbo - Warm Tonal)',
    provider: 'sahara',
    gender: 'female',
    accent: 'Enugu Central Igbo',
    language: 'ig',
    supportedStyles: ['Empathetic Clinical', 'Community Health'],
    recommendedFor: 'Maternal guidance, neonatal care tips, and rural outreach in Southeastern Nigeria.',
  },
  {
    id: 'sahara-ig-male-1',
    name: 'Emeka (Igbo - Resonant)',
    provider: 'sahara',
    gender: 'male',
    accent: 'Owerri Central Igbo',
    language: 'ig',
    supportedStyles: ['Professional Doctor', 'Healthcare Educator'],
    recommendedFor: 'Chronic illness management (hypertension/diabetes) and hospital navigation.',
  },
  {
    id: 'sahara-en-female-1',
    name: 'Ngozi (Nigerian English - Professional)',
    provider: 'sahara',
    gender: 'female',
    accent: 'Nigerian English (Medical Clinician)',
    language: 'en',
    supportedStyles: ['Clinical Professional', 'Clear Patient Explanation'],
    recommendedFor: 'Bilingual hospital consultations and pan-African medical instructions.',
  },
  {
    id: 'sahara-en-male-1',
    name: 'Femi (Nigerian English - Warm)',
    provider: 'sahara',
    gender: 'male',
    accent: 'Lagos Accented English',
    language: 'en',
    supportedStyles: ['Public Service', 'Informative'],
    recommendedFor: 'Community campaigns and emergency response instructions.',
  },

  // Gemini 3.1 Flash TTS Voices
  {
    id: 'gemini-kore',
    name: 'Kore (Gemini - Empathetic)',
    provider: 'gemini',
    gender: 'female',
    accent: 'Balanced International',
    language: 'en',
    supportedStyles: ['Empathetic', 'Calm', 'Instructional'],
    recommendedFor: 'Empathetic healthcare delivery, pediatric reassurance, and multilingual medical Q&A.',
  },
  {
    id: 'gemini-zephyr',
    name: 'Zephyr (Gemini - Clinical Warm)',
    provider: 'gemini',
    gender: 'female',
    accent: 'Modern Neutral',
    language: 'fr',
    supportedStyles: ['Clear Healthcare', 'Public Health'],
    recommendedFor: 'Francophone African healthcare information (Senegal, DRC, Côte d\'Ivoire).',
  },
  {
    id: 'gemini-puck',
    name: 'Puck (Gemini - Crisp Clear)',
    provider: 'gemini',
    gender: 'male',
    accent: 'Articulate Neutral',
    language: 'es',
    supportedStyles: ['Authoritative Medical', 'Engaging'],
    recommendedFor: 'Clear public service announcements and pharmacy dosage instructions.',
  },
  {
    id: 'gemini-fenrir',
    name: 'Fenrir (Gemini - Deep Resonant)',
    provider: 'gemini',
    gender: 'male',
    accent: 'Deep Neutral',
    language: 'hi',
    supportedStyles: ['Informative', 'Calm Guide'],
    recommendedFor: 'Community health instruction and long-form medical explainers.',
  },
  {
    id: 'gemini-charon',
    name: 'Charon (Gemini - Measured)',
    provider: 'gemini',
    gender: 'male',
    accent: 'Steady International',
    language: 'zh',
    supportedStyles: ['Educational', 'Professional'],
    recommendedFor: 'Scientific and technical clinical communications.',
  },

  // Browser Native Speech Fallback
  {
    id: 'browser-default-en',
    name: 'Device Native Voice (English)',
    provider: 'browser',
    gender: 'neutral',
    accent: 'Host OS Accent',
    language: 'en',
    recommendedFor: 'Immediate local playback when external APIs are not yet configured.',
  },
  {
    id: 'browser-default-fr',
    name: 'Device Native Voice (French)',
    provider: 'browser',
    gender: 'neutral',
    accent: 'Host OS French',
    language: 'fr',
    recommendedFor: 'Immediate local playback in French.',
  },
  {
    id: 'browser-default-es',
    name: 'Device Native Voice (Spanish)',
    provider: 'browser',
    gender: 'neutral',
    accent: 'Host OS Spanish',
    language: 'es',
    recommendedFor: 'Immediate local playback in Spanish.',
  },
];
